@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to running the cspybat command line utility
@REM using the appropriate settings.
@REM
@REM Note that this file and the accompanying launch.json file are generated
@REM every time the workspace is opened or a setting is changed, so you
@REM may want to move or rename the files before making changes.
@REM
@REM You can launch cspybat by typing the name of this this batch file,
@REM optionally followed by the name of the debug file
@REM (usually an ELF / DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases :
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign - on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"C:\iar\qtarm-10.2.1\common\bin\CSpyBat.exe" --launch_file "C:\ProgramData\IARSystems\EmbeddedWorkbench\DownloadedExamples\arm\9.70.4\ST\Spear3xx\EVALSPEAr300\GettingStarted\settings\launch.json" --launch_config "GettingStarted - DDR2 Debug" 

@echo off 
goto end 

:debugFile 

@echo on 

"C:\iar\qtarm-10.2.1\common\bin\CSpyBat.exe" --launch_file "C:\ProgramData\IARSystems\EmbeddedWorkbench\DownloadedExamples\arm\9.70.4\ST\Spear3xx\EVALSPEAr300\GettingStarted\settings\launch.json" --launch_config "GettingStarted - DDR2 Debug" --debug_file=%~1 

@echo off 
:end