param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C-SPY Debugger, as an aid to running the cspybat command line utility
# using the appropriate settings.
#
# Note that this file and the accompanying launch.json file are generated
# every time the workspace is opened or a setting is changed, so you
# may want to move or rename the files before making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the
# name of this batch file, optionally followed by the name of the debug
# file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C-SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\iar\qtarm-10.2.1\common\bin\CSpyBat.exe" --launch_file "C:\ProgramData\IARSystems\EmbeddedWorkbench\DownloadedExamples\arm\9.70.4\ST\Spear3xx\EVALSPEAr300\GettingStarted\settings\launch.json" --launch_config "GettingStarted - DDR2 Debug" 
}
else
{
& "C:\iar\qtarm-10.2.1\common\bin\CSpyBat.exe" --launch_file "C:\ProgramData\IARSystems\EmbeddedWorkbench\DownloadedExamples\arm\9.70.4\ST\Spear3xx\EVALSPEAr300\GettingStarted\settings\launch.json" --launch_config "GettingStarted - DDR2 Debug" --debug_file=$debugfile 
}
